//> using publish.organization "io.github.alexarchambault"
//> using publish.name "class-path-inspector"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central-s01"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/alexarchambault/class-path-inspector"
//> using publish.versionControl "github:alexarchambault/class-path-inspector"
//> using publish.developer "Alex Archambault||https://github.com/alexarchambault"
